fix: ivy compatibility
typebytes/ngx-template-streams pull request #12
Opened 2019-11-01 07:03 UTC by fxck

NG_COMPONENT_DEF -> NG_COMP_DEF

2019-11-01 17:07 UTC, d3lm requested changes
Thanks for the PR, really appreciate it! Left a comment on the readme note.

Also can you squash your commits into one and follow the commit convention? I suggest to go with something like:

`fix(lib): ivy compatibility`

Once that's done, I can merge it and publish a new release to npm.

2019-11-01 17:07 UTC, d3lm commented on README.md
> +- ✅ Works with both `ViewEngine` and `Ivy` (_note: if you want to use `ngx-template-streams` with **Ivy** you have to use the lastest version of `ngx-template-streams`_)
Could you add an `*` after Ivy and add the note below the features?

Here's how I would change it:

```text
- ✅ Works with both `ViewEngine` and `Ivy` [\*](#ivy-compatibility-note)

...

**Notes**

[<a id="ivy-compatibility-note"></a>1] If you want to use `ngx-template-streams` with **Ivy** you have to use the **lastest** version of `ngx-template-streams`.
```

2019-11-04 07:30 UTC, fxck commented
Done, should we change dependencies as well though?

2019-11-04 17:46 UTC, d3lm commented
Let's wait for that until Angular 9 is released. If it is I ll upgrade and cut a new release. Sounds good?

2019-11-04 17:47 UTC, fxck commented
👍

2019-11-04 17:48 UTC, merged

2019-11-04 18:30 UTC, d3lm commented
@fxck Can you give it a spin? I just published a new version.

2019-11-04 19:20 UTC, fxck commented
Looks good at the first glance.

2019-11-04 19:22 UTC, d3lm commented
Thanks for checking!